### ISSUE TITLE
Update to work with rails 5

### ISSUE THREAD

**Issue by valterbarros** [rachidcalazans/ar#13]

**Comment by Mirv** [comment]
@valterbarros 

How deep into rails 5 do you want to go?  Default if you just stick `rails` in the gem file is ...

```
mirv:~/workspace (master) $ rails -v
Rails 5.1.4
```

Ok?

**Comment by rachidcalazans** [comment]
@Mirv That issue is to update some part of code to be able on new version of Rails. Because the gem can create views, controllers, models and migrations.
